[project]
name = "dymola-python-interface-wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Julius Aka", email = "aka.julius@hotmail.de" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
dymola-python-docs = "dymola_python_interface_wrapper.open_docs:open_docs"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
