defaults: 
  - base_pModel

RawData:
  modelName: CartPole
  fmuPath: models/MechanicalTesters/CartPole_polar.fmu
  versionName: v1
  parameters:
    pendulum_start_rel: [-1.0, 1.0, 0.9]
    m: [1.0]
    M: [1.0]
    L: [1.0]
    # can be used for sampling initial states
    # vy_start:
    # vx_start:
    # xs_start:
    # vs_start:
  parameters_default_lower_factor: 0.2
  parameters_default_upper_factor: 5.0
  parameters_include: false
  parameters_sampling_strategy: R
  states:
    omega:
    theta:
    xs:
    vs:
  states_default_lower_value: 273.15
  states_default_upper_value: 473.15
  initial_states_include: false
  initial_states_sampling_strategy: R
  controls:
    Fs_x: [-2, 2]
  controls_include: true
  controls_sampling_strategy: RROCS
  controls_frequency_min_in_timesteps: 12
  controls_frequency_max_in_timesteps: 200
  outputs:
    - x
    - y
    - vx
    - vy
    - der(omega)
    - der(theta)
    - der(xs)
    - der(vs)
  Solver:
    simulationStartTime: 0.0
    simulationEndTime: 15.0
    timestep: 0.01
    tolerance: 1e-5
  n_samples: 512
dataset_prep:
  n_samples: [512]
  states:
    - all
  outputs: 
    - all
  parameters: # remove start parameters
    - m
    - M
    - L
  test_fraction: 0.12
  start_time: 0.0
  validation_fraction: 0.12