defaults: 
  - base_pModel

RawData:
  modelName: chaoticLorenz
  fmuPath: ../modelica/KoopmanTester/KoopmanTester_chaotic_0lorenz_0system_chaoticLorenz.fmu
  versionName: v1
  # parameters:
  #   lambda: [-10, -0.01, -1]
  #   mu: [-10, -0.01, -0.5]
  parameters_default_lower_factor: 0.2
  parameters_default_upper_factor: 5.0
  parameters_include: false
  parameters_sampling_strategy: R
  states:
    x: [-25, 25]
    y: [-25, 25]
    z: [-25, 25]
  initial_states_include: true
  initial_states_sampling_strategy: R
  # controls:
  #   u: [-100, 100]
  controls_include: false
  controls_sampling_strategy: RROCS
  controls_frequency_min_in_timesteps: 6
  controls_frequency_max_in_timesteps: 30
  # outputs:
  #   - 
  Solver:
    simulationStartTime: 0.0
    simulationEndTime: 10.0
    timestep: 0.05
    tolerance: 1e-5
  n_samples: 100
dataset_prep:
  n_samples: [100]
  states:
    - all
  outputs: 
    - all
  test_fraction: 0.12
  start_time: 0.0
  validation_fraction: 0.12