defaults: 
  - base_pModel

RawData:
  modelName: ThreeStratifiedHeatFlowModel
  fmuPath: models/ThermalTesters/ThreeStratifiedHeatFlowModels_parameterCalibration.fmu
  versionName: v3
  parameters:
    C1: [2.0]
    R1: [1.0]
    C2: [1.0]
    R2: [2.0]
    C3: [1.0]
    R3: [1.0]
  parameters_default_lower_factor: 0.2
  parameters_default_upper_factor: 5.0
  parameters_include: true
  parameters_sampling_strategy: R
  states:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[1].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[2].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[3].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[4].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[5].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[6].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[7].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[8].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[9].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[10].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[1].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[2].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[3].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[4].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[5].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[6].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[7].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[8].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[9].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[10].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[1].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[2].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[3].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[4].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[5].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[6].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[7].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[8].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[9].heatCapacitor.T:
    threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[10].heatCapacitor.T:
  controls_include: false
  outputs:
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[1].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[1].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[1].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[2].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[2].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[2].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[3].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[3].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[3].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[4].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[4].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[4].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[5].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[5].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[5].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[6].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[6].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[6].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[7].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[7].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[7].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[8].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[8].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[8].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[9].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[9].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[9].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[10].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[10].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow1.partition[10].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[1].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[1].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[1].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[2].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[2].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[2].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[3].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[3].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[3].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[4].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[4].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[4].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[5].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[5].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[5].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[6].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[6].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[6].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[7].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[7].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[7].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[8].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[8].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[8].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[9].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[9].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[9].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[10].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[10].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow2.partition[10].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[1].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[1].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[1].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[2].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[2].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[2].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[3].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[3].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[3].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[4].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[4].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[4].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[5].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[5].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[5].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[6].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[6].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[6].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[7].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[7].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[7].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[8].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[8].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[8].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[9].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[9].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[9].thermalResistor.port_b.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[10].heatCapacitor.port.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[10].thermalResistor.port_a.Q_flow
    - threeStratifiedHeatFlowModels.stratifiedHeatFlow3.partition[10].thermalResistor.port_b.Q_flow
  Solver:
    simulationStartTime: 0.0
    simulationEndTime: 1.0
    timestep: 0.01
    tolerance: 1e-6
  n_samples: 256
dataset_prep:
  n_samples: [256]
  states:
    - all
  outputs: 
    - all
  test_fraction: 0.12
  start_time: 0.00
  validation_fraction: 0.12