defaults: 
  - base_pModel

RawData:
  modelName: SimpleSeriesResonance
  fmuPath: models/SeriesResonanceTesters/SeriesResonanceTesters_SimpleSeriesResonance.fmu
  versionName: v4
  parameters:
    L: [0.0159155]
    C: [0.000159155]
    R: [0.5]
  parameters_default_lower_factor: 0.2
  parameters_default_upper_factor: 5.0
  parameters_include: false
  parameters_sampling_strategy: R
  states:
    inductor1.i: [-10, 10]
    capacitor1.v: [-100, 100]
  initial_states_include: false
  initial_states_sampling_strategy: R
  controls:
    u: [-100, 100]
  controls_include: true
  controls_sampling_strategy: RROCS
  controls_frequency_min_in_timesteps: 6
  controls_frequency_max_in_timesteps: 30
  outputs:
    - resistor1.v
    - resistor1.i
    - resistor1.LossPower
    - inductor1.v
    - capacitor1.i
  Solver:
    simulationStartTime: 0.0
    simulationEndTime: 0.6
    timestep: 2e-4
    tolerance: 1e-6
  n_samples: 256
dataset_prep:
  n_samples: [256]
  states:
    - all
  outputs: 
    - all
  test_fraction: 0.12
  start_time: 0.1
  validation_fraction: 0.5